language: go

go:
  - "1.23.x"

branches:
  only:
    - master
    - stable
    - dev
env:
  - GO111MODULE=on

install: true

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - curl https://raw.githubusercontent.com/go-gilbert/gilbert/master/install.sh | sh

script:
  - go vet ./...
  - golangci-lint run
  - go test ./...
  - gilbert run cover
  - gilbert run build