language: go

go:
  - "1.11.x"
  - "1.12.x"

branches:
  only:
    - master
    - stable
    - dev
env:
  - GO111MODULE=on

install: true

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - go vet ./...
  - golangci-lint run
  - go test ./...
  - go build -o ./gilbert-dev
  - ./gilbert-dev run build