language: go

go:
  - "1.10.x"
  - "1.11.x"

branches:
  only:
    - master
    - stable
    - dev

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -L https://git.io/vp6lP | sh
  - go get -u github.com/alexkohler/prealloc
  - go get -u github.com/hypnoglow/durcheck
  - go get -u github.com/m3db/build-tools/linters/badtime
  - go get -u https://github.com/kisielk/errcheck

install:
  - dep ensure

before_script:
  - go vet ./..
  - gometalinter ./...

script:
  - go test ./...
  - go build -o ./gilbert-dev
  - ./gilbert-dev run release